dtbo-$(CONFIG_ARCH_KALAMA) += ../../qcom/display/display/kalama-sde.dtbo \
		display/kalama-sde-display-ayn-odin2-overlay.dtbo \
		display/kalama-sde-display-ayn-odin2-mini-overlay.dtbo \
		display/kalama-sde-display-ayn-odin2-portal-overlay.dtbo \
		display/kalama-sde-display-ayn-odin2-thor-overlay.dtbo \
		display/kalama-sde-display-retroid-pocket-6-overlay.dtbo

always-y    := $(dtb-y) $(dtbo-y)
subdir-y    := $(dts-dirs)
clean-files    := *.dtb *.dtbo
